--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Wed Mar 14 2018
--=======================================================================================
require("typescript_lualib")
_G.options={AllowDuplicatePicksInRound=false,AllowDuplicatePicksForPlayers=false,AllRandom=false,KillsToEndRound=10,ShrinkingWalls=false,HeroSelectionTime=15}
