--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Wed Mar 14 2018
--=======================================================================================
require("typescript_lualib")
_G["VectorTargetListener"]=(_G["VectorTargetListener"] or CustomGameEventManager:RegisterListener("vector_targetted_ability_cast_finished",ExecuteVectorTargetAbility))
function ExecuteVectorTargetAbility(pID,data)
    local startPos = Vector(data.startPos["0"],data.startPos["1"],data.startPos["2"])

    local endPos = Vector(data.endPos["0"],data.endPos["1"],data.endPos["2"])

    local points = {}

    TS_forEach(data.allPoints, function(point)
        TS_push(points, Vector(point["0"],point["1"],point["2"]))
    end
)
    local ability = EntIndexToHScript(data.abilityIndex)

    local hero = ability:GetCaster()

    ability.startPos=startPos
    ability.endPos=endPos
    ability.points=points
    hero:CastAbilityNoTarget(ability,hero:GetPlayerOwnerID())
end
