--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Wed Mar 14 2018
--=======================================================================================
require("typescript_lualib")
LinkLuaModifier("modifier_zone_dummy","zones.lua",LUA_MODIFIER_MOTION_NONE)
modifier_zone_dummy = {}
modifier_zone_dummy.__index = modifier_zone_dummy
function modifier_zone_dummy.new(construct, ...)
    local instance = setmetatable({}, modifier_zone_dummy)
    if construct and modifier_zone_dummy.constructor then modifier_zone_dummy.constructor(instance, ...) end
    return instance
end
function modifier_zone_dummy.IsPermanent(self)
    return true
end
function modifier_zone_dummy.GetAuraRadius(self)
    return 190
end
function modifier_zone_dummy.DeclareFunctions(self)
    return {}
end
function modifier_zone_dummy.GetModifierModelChange(self)
    return "models/item_zone.vmdl"
end
function modifier_zone_dummy.OnCreated(self,kv)
    self.particle=kv.pIndex
    self:StartIntervalThink(FrameTime())
end
function modifier_zone_dummy.OnIntervalThink(self)
    local parent = self:GetParent()

    local units = FindUnitsInRadius(parent:GetTeamNumber(),parent:GetAbsOrigin(),nil,self:GetAuraRadius(),DOTA_UNIT_TARGET_TEAM_BOTH,DOTA_UNIT_TARGET_HERO,DOTA_UNIT_TARGET_FLAG_NONE,FIND_ANY_ORDER,false)

    if #units==1 then
        local unit = units[0+1]

        parent:SetHealth(parent:GetHealth()-1)
        for i=0,DOTA_TEAM_CUSTOM_MAX,1 do
            if PlayerResource:GetPlayerCountForTeam(i)>0 then
                AddFOWViewer(i,parent:GetAbsOrigin(),self:GetAuraRadius(),FrameTime()*3,false)
            end
        end
        if parent:GetHealth()<=0 then
            CreatePhysicsItem(GetRandomItemName(),unit:GetAbsOrigin())
            ParticleManager:DestroyParticle(self.particle,false)
            ParticleManager:ReleaseParticleIndex(self.particle)
            local parentOrigin = parent:GetAbsOrigin()

            UTIL_Remove(parent)
            Timers:CreateTimer(15,function()
                CreateItemZone(parentOrigin)
            end
)
            return
        end
    else
        if #units==0 then
            parent:SetHealth(math.min(parent:GetMaxHealth(),parent:GetHealth()+1))
        else
            parent:SetHealth(math.min(parent:GetMaxHealth(),parent:GetHealth()+1))
            for i=0,DOTA_TEAM_CUSTOM_MAX,1 do
                if PlayerResource:GetPlayerCountForTeam(i)>0 then
                    AddFOWViewer(i,parent:GetAbsOrigin(),self:GetAuraRadius(),FrameTime()*3,false)
                end
            end
        end
    end
end
function CreateItemZone(location)
    local dummy = CreateUnitByName("npc_dummy_unit",location,false,nil,nil,DOTA_TEAM_NEUTRALS)

    local particle = ParticleManager:CreateParticle("particles/ping_waypoint_drop.vpcf",PATTACH_ABSORIGIN,dummy)

    dummy:AddNewModifier(nil,nil,"modifier_zone_dummy",{pIndex=particle})
    return dummy
end
