--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Tue Mar 13 2018
--=======================================================================================
require("typescript_lualib")
require("items/base_item")
LinkLuaModifier("modifier_charges_tree_toss","items/item_tree_toss.lua",LUA_MODIFIER_MOTION_NONE)
item_spell_tree_toss = item_base_item.new()
item_spell_tree_toss.__index = item_spell_tree_toss
item_spell_tree_toss.__base = item_base_item
function item_spell_tree_toss.new(construct, ...)
    local instance = setmetatable({}, item_spell_tree_toss)
    if construct and item_spell_tree_toss.constructor then item_spell_tree_toss.constructor(instance, ...) end
    return instance
end
modifier_charges_tree_toss = modifier_charges_base_item.new()
modifier_charges_tree_toss.__index = modifier_charges_tree_toss
modifier_charges_tree_toss.__base = modifier_charges_base_item
function modifier_charges_tree_toss.new(construct, ...)
    local instance = setmetatable({}, modifier_charges_tree_toss)
    if construct and modifier_charges_tree_toss.constructor then modifier_charges_tree_toss.constructor(instance, ...) end
    return instance
end
