--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Wed Mar 14 2018
--=======================================================================================
require("typescript_lualib")
require("abilities/base_ability")
impetus = base_ability.new()
impetus.__index = impetus
impetus.__base = base_ability
function impetus.new(construct, ...)
    local instance = setmetatable({}, impetus)
    if construct and impetus.constructor then impetus.constructor(instance, ...) end
    return instance
end
function impetus.OnSpellStart(self)
    local caster = self:GetCaster()

    local dummy = SpawnEntityFromTableSynchronous("prop_dynamic",{model="models/development/invisiblebox.vmdl",targetname=DoUniqueString("prop_dynamic")})

    dummy:SetAbsOrigin(caster:GetAbsOrigin())
    local projectileTable = {flRadius=self:GetSpecialValueFor("radius"),hCaster=self:GetCaster(),hTarget=dummy,flSpeed=self:GetProjectileSpeed(),flTurnRate=1000,sEffectName="particles/units/heroes/hero_enchantress/enchantress_impetus_orig.vpcf",WallBehavior=PROJECTILES_DESTROY,TreeBehavior=PROJECTILES_DESTROY,UnitBehavior=PROJECTILES_DESTROY,ItemBehavior=PROJECTILES_IGNORE,UnitTest=function(projectile,unit,caster)
        return self:UnitTest(projectile,unit,caster)
    end
,OnUnitHit=function(projectile,unit,caster)
        local distance = projectile.distanceTravelled

        local dmgTable = {attacker=caster,ability=self,victim=unit,damage=distance/10,damage_type=DAMAGE_TYPE_MAGICAL}

        ApplyDamage(dmgTable)
    end
,OnProjectileThink=function(projectile,location)
        if projectile["pointCount"]==projectile["points"].length then
            Physics2D:DestroyProjectile(projectile)
            return
        end
        if LengthSquared(location-projectile["points"][projectile["pointCount"]])<25 then
            projectile["pointCount"]=(projectile["pointCount"]+1)
            projectile.target:SetAbsOrigin(projectile["points"][projectile["pointCount"]])
        end
    end
}

    local projectile = Physics2D:CreateTrackingProjectile(projectileTable)

    projectile["points"]=self.points
    projectile["pointCount"]=0
end
