--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Tue Mar 13 2018
--=======================================================================================
require("typescript_lualib")
require("abilities/base_ability")
spellsteal = base_ability.new()
spellsteal.__index = spellsteal
spellsteal.__base = base_ability
function spellsteal.new(construct, ...)
    local instance = setmetatable({}, spellsteal)
    if construct and spellsteal.constructor then spellsteal.constructor(instance, ...) end
    return instance
end
function spellsteal.GetProjectileParticleName(self)
    return "particles/units/heroes/hero_rubick/rubick_spell_steal.vpcf"
end
function spellsteal.GetProjectileUnitBehavior(self)
    return PROJECTILES_DESTROY
end
function spellsteal.GetProjectileWallBehavior(self)
    return PROJECTILES_BOUNCE
end
function spellsteal.GetProjectileItemBehavior(self)
    return PROJECTILES_IGNORE
end
function spellsteal.GetSound(self)
    return "Hero_Rubick.SpellSteal.Cast"
end
function spellsteal.OnProjectileHitUnit(self,projectile,target,caster)
    target:EmitSound("Hero_Rubick.SpellSteal.Target")
    local spells = {}

    local randomSpell = target:GetAbilityByIndex(1)

    local abilityName = nil

    local modifierName = nil

    local oldStackCount = 0

    abilityName=randomSpell:GetAbilityName()
    local pTable = {hCaster=caster,hTarget=caster,vSpawnOrigin=target:GetAbsOrigin(),flRadius=1,flSpeed=self:GetProjectileSpeed(),flTurnRate=100,UnitBehavior=PROJECTILES_DESTROY,sEffectName=self:GetProjectileParticleName(),UnitTest=function(projectile,target,caster)
        return target==caster
    end
,OnUnitHit=function(projectile,target,caster)
        caster:EmitSound("Hero_Rubick.SpellSteal.Complete")
        CreatePhysicsItem("item_spell_" .. abilityName,caster:GetAbsOrigin())
    end
}

    local proj = Physics2D:CreateTrackingProjectile(pTable)

end
